### PR TITLE
[BUGFIX] Early return on empty menu

### LINKED ISSUE #1278: Page/Menu/BrowseViewHelper does not properly handle empty menu data
In my page template I have this:

```
<v:page.menu.browse as="pages" doktypes="DEFAULT,LINK,SHORTCUT,MOUNTPOINT,111">
```

This crashes when parent of current page has only "not in menu" child pages:

structure

This may be fixed with a simple test within `\FluidTYPO3\Vhs\ViewHelpers\Menu\BrowseViewHelper::render`:

```
        $menuData = $this->getMenu($parentUid);
        if (empty($menuData)) return null;
```

since `$menuData` is null for such a use case.

### PR DESCRIPTION
**Pull request by bjo3rnf**
Fixes #1278

### CODE REVIEW

File: Classes/ViewHelpers/Menu/BrowseViewHelper.php [hunk 1]
```diff
@@ -90,6 +90,9 @@ public function render()
         $parentUid = (integer) (null !== $this->arguments['pageUid'] ? $pageUid : $currentPage['pid']);
         $parentPage = $this->pageService->getPage($parentUid, $showAccessProtected);
         $menuData = $this->getMenu($parentUid);
+        if (empty($menuData)) {
```
Comment (NamelessCoder) [inline Classes/ViewHelpers/Menu/BrowseViewHelper.php]: We may need to return either an empty string or if the `as` argument is used, return `$this->renderChildren()` without assigning the variable. Otherwise, custom rendering of empty menus gets disabled (no option to render a "no menu items" message for example).

Comment (bjo3rnf) [inline Classes/ViewHelpers/Menu/BrowseViewHelper.php]: So true, thanks.
